fragment GlobalParts on Global {
  gtmId
  redirects {
    __typename
    from
    to
  }
}

fragment PagesParts on Pages {
  draft
  blocks {
    __typename
    ... on PagesBlocksFeature {
      style {
        __typename
        minHeight
        flipLayout
        textAlignment
        contentAlignment
        fillStyles
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      image {
        __typename
        src
        alt
        imageStyle
        fit
        position
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        textColor
        backgroundColor
      }
      navigationLabel
    }
    ... on PagesBlocksPhotoCards {
      style {
        __typename
        minHeight
        columns
        textAlignment
        fillStyles
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
        contentWidth
      }
      cardStyle {
        __typename
        type
        imageStyles
        fillStyles
        accentColor
        padding
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonType
        buttonTextColor
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        textColor
        backgroundColor
      }
      items {
        __typename
        image {
          __typename
          src
          alt
        }
        headline
        subhead
        text
        link
        buttonLabel
      }
      navigationLabel
    }
    ... on PagesBlocksTextCards {
      style {
        __typename
        minHeight
        columns
        textAlignment
        fillStyles
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
        contentWidth
      }
      cardStyle {
        __typename
        type
        fillStyles
        accentColor
        padding
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonType
        buttonTextColor
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        textColor
        backgroundColor
      }
      items {
        __typename
        headline
        subhead
        text
        link
        buttonLabel
        accentColor
      }
      navigationLabel
    }
    ... on PagesBlocksBanner {
      image {
        __typename
        src
        alt
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        textColor
        backgroundColor
      }
      navigationLabel
      style {
        __typename
        minHeight
        textAlignment
        width
        fillStyles
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
    }
  }
  meta {
    __typename
    siteTitle
    siteDescription
    siteImageSrc
  }
  nav {
    __typename
    navItems {
      __typename
      label
      link
    }
    navTextColor
    navBackgroundColor
  }
  colors {
    __typename
    primary
    accent1
    accent2
    accent3
    accent4
    white
    grayLight
    gray
    grayDark
    black
  }
}
