fragment GlobalParts on Global {
  siteUrl
  gtmId
  redirects {
    __typename
    from
    to
  }
}

fragment PagesParts on Pages {
  draft
  blocks {
    __typename
    ... on PagesBlocksFeature {
      style {
        __typename
        fillStyles
        alignment
        contentTitle
        featureContent
        padding
        imageTitle
        featureImage
        imagePadding
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      image {
        __typename
        src
        alt
        imageStyle
        fit
        position
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        buttonFillStyles
        textColor
        backgroundColor
      }
      navigationLabel
    }
    ... on PagesBlocksPhotoCards {
      style {
        __typename
        fillStyles
        textAlignment
        minHeight
        padding
        contentWidth
        columns
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      cardStyle {
        __typename
        fillStyles
        padding
        type
        accentColor
        imageStyles
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonTitle
        buttonType
        buttonFillStyles
        buttonTextColor
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        buttonFillStyles
        textColor
        backgroundColor
      }
      items {
        __typename
        image {
          __typename
          src
          alt
        }
        headline
        subhead
        text
        link
        buttonLabel
      }
      navigationLabel
    }
    ... on PagesBlocksTextCards {
      style {
        __typename
        fillStyles
        textAlignment
        minHeight
        padding
        contentWidth
        columns
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      cardStyle {
        __typename
        fillStyles
        padding
        type
        accentColor
        borderStyles
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonTitle
        buttonType
        buttonTextColor
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        buttonFillStyles
        textColor
        backgroundColor
      }
      items {
        __typename
        headline
        subhead
        text
        link
        buttonLabel
        accentColor
      }
      navigationLabel
    }
    ... on PagesBlocksBanner {
      style {
        __typename
        fillStyles
        textAlignment
        minHeight
        padding
        width
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      image {
        __typename
        src
        alt
      }
      backgroundImage {
        __typename
        src
        position
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
        buttonFillStyles
        textColor
        backgroundColor
      }
      navigationLabel
    }
    ... on PagesBlocksEmbed {
      style {
        __typename
        minHeight
        fullWidth
        padding
        fillStyles
      }
      backgroundImage {
        __typename
        src
        position
      }
      markup
      navigationLabel
    }
  }
  meta {
    __typename
    siteTitle
    siteDescription
    siteImageSrc
  }
  nav {
    __typename
    navItems {
      __typename
      label
      link
    }
    navAlignment
    navTextColor
    navBackgroundColor
  }
  colors {
    __typename
    primary
    accent1
    accent2
    accent3
    accent4
    white
    grayLight
    gray
    grayDark
    black
  }
}
